### ISSUE TITLE
which numba version is used?

### ISSUE THREAD

**Issue by vesuppi** [spcl/npbench#18]
Hi, I was trying to play with npbench and tried quickstart.py and got a plot. However, I do see that for every benchmark there exists multiple numba versions, I was wondering which implementation does framework `numba` refers to, when we do `frameworks = ["numpy", "numba"]`? I assume it's `xxx_numba_npr.py`? since it's nopython mode and uses parallel range, and should run faster than other numba versions? However, not all benchmarks have a `numba_npr` version though. 

Or perhaps the best of all implementations is reported as framework `numba`?

Thanks!

**Comment by alexnick83** [comment]
Hello!

All available versions of numba are tested. There can be up to 6 versions (combinations of nopython/object mode, parallel True/False, and explicitly using numba.prange or not). We do not include versions that are redundant or consistently fail to run or deadlock. For example, if a sample runs with numba in nopython mode without any code changes, then there is no point in having an object mode (compatibility) version.

When plotting the results, the version used is the one having the best median runtime out of those that were successfully validated.

**Comment by vesuppi** [comment]
Ah I see, thank you very much for the explanation!
