### ISSUE TITLE
Seemly bugs found in npbench code

### ISSUE THREAD

**Issue by vesuppi** [spcl/npbench#19]
Hi, as I was working with npbench recently, I have found the following seemly bugs:

# cholesky

Code: https://github.com/spcl/npbench/blob/857a7ec2d267e255bfcd9bad296be1cbf4e81178/npbench/benchmarks/polybench/cholesky/cholesky_numba_npr.py#L10-L13

Line 10 is a prange, but actually this loop is not parallel due to the data dependence on `A[i,:j]`. To correct this `nb.prange` should be just `range`. 

I also noticed that for this loop Numba (most recent version) seems not compile to nopython mode with `@nb.jit(nopython=True, parallel=True, fastmath=True)`, but removing `parallel=True` gets the code compiled to nopython mode. 

Also the validation for cholesky always passes no matter what. I support it could be due to that the kernel function doesn't return anything.

Actually not just `cholesky` doesn't return anything, many other benchmarks as well, like syrk etc. So they may also always pass validation no matter what.

**Comment by alexnick83** [comment]
Hello! Thank you for reporting these issues.

> Line 10 is a prange, but actually this loop is not parallel due to the data dependence on A[i,:j]. To correct this nb.prange should be just range.

Good catch; the prange should be on the outer loop.

> I also noticed that for this loop Numba (most recent version) seems not compile to nopython mode with @nb.jit(nopython=True, parallel=True, fastmath=True), but removing parallel=True gets the code compiled to nopython mode.

A version with `parallel=False` is already included, but we will also fix the one with the erroneous parallelization.

> Also the validation for cholesky always passes no matter what. I support it could be due to that the kernel function doesn't return anything.
> Actually not just cholesky doesn't return anything, many other benchmarks as well, like syrk etc. So they may also always pass validation no matter what.

There is functionality in the benchmark that allows marking kernel parameters as both input and output. These parameters are also validated. Cholesky's `A` parameter is marked as such, but there may be some other bug that breaks validation in that case. We will investigate.

**Comment by vesuppi** [comment]
Thanks a lot for confirming!
